services:
  bitcoin:
    image: ghcr.io/getumbrel/umbrel-bitcoin:v1.3.0@sha256:a684213f37985b987c07a4d10cc9d04396eb2eb2a25f6b210052bb102950d7fe
    restart: always
    stop_grace_period: 15m30s
    ports:
      - "2100:3000"
      - "${APP_BITCOIN_P2P_PORT}:${APP_BITCOIN_P2P_PORT}"
      - "${APP_BITCOIN_RPC_PORT}:${APP_BITCOIN_RPC_PORT}"
    volumes:
      - ${BITCOIN_DRIVE}/bitcoin:/data
    environment:
      BITCOIND_EXTRA_ARGS: "-deprecatedrpc=create_bdb,-dbcache=96,-maxmempool=64,-maxconnections=40,-par=1"
      APPS_SUBNET: "${NETWORK_IP}/16"
      P2P_PORT: "${APP_BITCOIN_P2P_PORT}"
      P2P_WHITEBIND_PORT: "${APP_BITCOIN_P2P_WHITEBIND_PORT}"
      RPC_PORT: "${APP_BITCOIN_RPC_PORT}"
      TOR_PORT: "${APP_BITCOIN_TOR_PORT}"
      ZMQ_RAWBLOCK_PORT: "${APP_BITCOIN_ZMQ_RAWBLOCK_PORT}"
      ZMQ_RAWTX_PORT: "${APP_BITCOIN_ZMQ_RAWTX_PORT}"
      ZMQ_HASHBLOCK_PORT: "${APP_BITCOIN_ZMQ_HASHBLOCK_PORT}"
      ZMQ_SEQUENCE_PORT: "${APP_BITCOIN_ZMQ_SEQUENCE_PORT}"
      ZMQ_HASHTX_PORT: "${APP_BITCOIN_ZMQ_HASHTX_PORT}"
      TOR_HOST: "${APP_BITCOIN_TOR_PROXY_IP}"
      TOR_SOCKS_PORT: "9050"
      TOR_CONTROL_PORT: "9051"
      TOR_CONTROL_PASSWORD: "moneyprintergobrrr"
      I2P_HOST: "${APP_BITCOIN_I2P_DAEMON_IP}"
      I2P_SAM_PORT: "7656"
      BITCOIND_IP: "${APP_BITCOIN_NODE_IP}"
      RPC_USER: "${APP_BITCOIN_RPC_USER}"
      RPC_PASS: "${APP_BITCOIN_RPC_PASS}"
      DEVICE_DOMAIN_NAME: "${DEVICE_DOMAIN_NAME}"
      P2P_HIDDEN_SERVICE: "notset.onion"
      RPC_HIDDEN_SERVICE: "notset.onion"
    networks:
      umbrel_main_network:
        ipv4_address: ${APP_BITCOIN_NODE_IP}

  electrs:
    image: getumbrel/electrs:v0.11.1@sha256:f1d5d4e431d39e0aaa0697014d2852880183e350ffcad612edb87183f0c11b25
    user: "0:0"
    restart: always
    depends_on:
      - bitcoin
    environment:
      ELECTRS_LOG_FILTERS: "INFO"
      ELECTRS_NETWORK: "${APP_BITCOIN_NETWORK_ELECTRS}"
      ELECTRS_DAEMON_DIR: "/data/.bitcoin/bitcoin"
      ELECTRS_COOKIE_FILE: "/data/.bitcoin/bitcoin/.cookie"
      ELECTRS_DAEMON_RPC_ADDR: "${APP_BITCOIN_NODE_IP}:${APP_BITCOIN_RPC_PORT}"
      ELECTRS_DAEMON_P2P_ADDR: "${APP_BITCOIN_NODE_IP}:${APP_BITCOIN_P2P_WHITEBIND_PORT}"
      ELECTRS_ELECTRUM_RPC_ADDR: "0.0.0.0:${APP_ELECTRS_NODE_PORT}"
      ELECTRS_SERVER_BANNER: "Umbrel Electrs (mini)"
      ELECTRS_DB_DIR: "/data/db"
    volumes:
      - ${BITCOIN_DRIVE}/bitcoin:/data/.bitcoin:ro
      - ${BITCOIN_DRIVE}/electrs:/data
    ports:
      - "${APP_ELECTRS_NODE_PORT}:${APP_ELECTRS_NODE_PORT}"
    networks:
      umbrel_main_network:
        ipv4_address: ${APP_ELECTRS_NODE_IP}

  electrs-ui:
    image: getumbrel/umbrel-electrs:v1.0.4@sha256:fa2fd04f4c7515aad84f21640f5feab1417bc18e20bc65cda7ed97e59b8458db
    restart: always
    depends_on:
      - electrs
    environment:
      ELECTRUM_HIDDEN_SERVICE: "notset.onion"
      ELECTRUM_LOCAL_SERVICE: "${DEVICE_DOMAIN_NAME}"
      ELECTRS_HOST: "${APP_ELECTRS_NODE_IP}"
      BITCOIN_HOST: "${APP_BITCOIN_NODE_IP}"
      RPC_USER: "${APP_BITCOIN_RPC_USER}"
      RPC_PASSWORD: "${APP_BITCOIN_RPC_PASS}"
      RPC_PORT: "${APP_BITCOIN_RPC_PORT}"
    ports:
      - "2102:3006"
    networks:
      umbrel_main_network:
        ipv4_address: 10.21.21.24

  mempool-db:
    image: mariadb:10.5.29@sha256:a530aeeefd82f4fa5150f391b6c75462140904780338766f6b03acecb1cca3ce
    restart: always
    stop_grace_period: 1m
    volumes:
      - ${BITCOIN_DRIVE}/mempool-db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "mempool"
      MYSQL_USER: "mempool"
      MYSQL_PASSWORD: "mempool"
      MYSQL_ROOT_PASSWORD: "moneyprintergobrrr"
    networks:
      umbrel_main_network:
        ipv4_address: ${APP_MEMPOOL_DB_IP}

  mempool-api:
    image: mempool/backend:v3.3.1@sha256:358c0a517c8dcf26e7f5c02447de5bab33ec7e3fa6318685cf8012ce36098e3a
    init: true
    restart: always
    stop_grace_period: 1m
    depends_on:
      - bitcoin
      - electrs
      - mempool-db
    command: "./wait-for-it.sh mempool-db:3306 --timeout=720 --strict -- ./start.sh"
    volumes:
      - ${BITCOIN_DRIVE}/mempool-cache:/backend/cache
    environment:
      CORE_RPC_HOST: ${APP_BITCOIN_NODE_IP}
      CORE_RPC_PORT: ${APP_BITCOIN_RPC_PORT}
      CORE_RPC_USERNAME: ${APP_BITCOIN_RPC_USER}
      CORE_RPC_PASSWORD: ${APP_BITCOIN_RPC_PASS}
      ELECTRUM_HOST: ${APP_ELECTRS_NODE_IP}
      ELECTRUM_PORT: ${APP_ELECTRS_NODE_PORT}
      ELECTRUM_TLS: "false"
      DATABASE_HOST: ${APP_MEMPOOL_DB_IP}
      DATABASE_PORT: "3306"
      DATABASE_DATABASE: "mempool"
      DATABASE_USERNAME: "mempool"
      DATABASE_PASSWORD: "mempool"
      MEMPOOL_HTTP_PORT: "8999"
      MEMPOOL_CACHE_DIR: "/backend/cache"
      MEMPOOL_CLEAR_PROTECTION_MINUTES: "20"
      MEMPOOL_INDEXING_BLOCKS_AMOUNT: "52560"
      MEMPOOL_STDOUT_LOG_MIN_PRIORITY: "info"
      LIGHTNING_ENABLED: "false"
      NODE_OPTIONS: "--max-old-space-size=512"
    networks:
      umbrel_main_network:
        ipv4_address: ${APP_MEMPOOL_API_IP}

  mempool-web:
    image: mempool/frontend:v3.3.1@sha256:0a162e7e0d26a01e9686ddf69c96c4beae5fe10b0daa1020f3d392e033c058f1
    init: true
    restart: always
    stop_grace_period: 1m
    depends_on:
      - mempool-db
      - mempool-api
    command: "./wait-for mempool-db:3306 --timeout=720 -- nginx -g 'daemon off;'"
    environment:
      FRONTEND_HTTP_PORT: ${APP_MEMPOOL_PORT}
      BACKEND_MAINNET_HTTP_HOST: ${APP_MEMPOOL_API_IP}
      NGINX_PORT: ${APP_MEMPOOL_PORT}
      NGINX_HOSTNAME: ${APP_MEMPOOL_API_IP}
      LIGHTNING_DETECTED_PORT: 0
    ports:
      - "${APP_MEMPOOL_PORT}:${APP_MEMPOOL_PORT}"
    networks:
      umbrel_main_network:
        ipv4_address: ${APP_MEMPOOL_IP}

networks:
  umbrel_main_network:
    name: umbrel_main_network
    driver: bridge
    ipam:
      config:
        - subnet: ${NETWORK_IP}/16
